### ISSUE TITLE
logger.php テーブルが見つからない

### ISSUE THREAD

**Issue by depra95** [eisen-dev/eisen_front#48]
monologテーブルが初期セットアップ(init-setup.php)で作成されていないので、表示できる内容が無い場合、logger.phpにアクセスした際に以下のエラーが出ます。
logger.phpのエラー：
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'eisen.monolog' doesn't exist' in /vagrant/webd/includes/DbAction.php:453 Stack trace: #0 /vagrant/webd/includes/DbAction.php(453): PDO->prepare('SELECT * FROM m...') #1 /vagrant/webd/logger.php(83): DbAction->monologList(Object(PDO)) #2 {main} thrown in /vagrant/webd/includes/DbAction.php on line 453

**Comment by aliceinwire** [comment]
fixed by pull request
