### ISSUE TITLE
ターゲットをまだ未登録の状態で「Logger」の画面でエラーが出る

### ISSUE THREAD

**Issue by ytooyama** [eisen-dev/eisen_front#56]
以下からの続きです。
https://github.com/eisen-dev/eisen_docs/issues/4

パッケージログ画面
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'created_at' in 'order clause'' in /vagrant/webd/includes/DbAction.php:476 Stack trace: #0 /vagrant/webd/includes/DbAction.php(476): PDO->prepare('SELECT * FROM p...') #1 /vagrant/webd/packageResult.php(97): DbAction->packageActionResult(Object(PDO)) #2 {main} thrown in /vagrant/webd/includes/DbAction.php on line 476

エラーログ画面
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'eisen.monolog' doesn't exist' in /vagrant/webd/includes/DbAction.php:462 Stack trace: #0 /vagrant/webd/includes/DbAction.php(462): PDO->prepare('SELECT * FROM m...') #1 /vagrant/webd/logger.php(94): DbAction->monologList(Object(PDO)) #2 {main} thrown in /vagrant/webd/includes/DbAction.php on line 462

![2016-03-01 06 10 11 00001](https://cloud.githubusercontent.com/assets/6257157/13419438/9e9e4f54-dfc1-11e5-836a-0e4d4e0cdd3c.png)
![2016-03-01 06 10 02 00001](https://cloud.githubusercontent.com/assets/6257157/13419435/958a41b6-dfc1-11e5-82d0-524941fb85cb.png)

**Comment by aliceinwire** [comment]
https://github.com/eisen-dev/eisen_front/issues/48

**Comment by aliceinwire** [comment]
fixed by pull request
