### ISSUE TITLE
Firefox 38.6.1でtarget host listの「新規マシン追加」やその横の「歯車」ボタンを押しても何も起こらない

### ISSUE THREAD

**Issue by ytooyama** [eisen-dev/eisen_front#57]
Firefox 38.6.1でtarget host listの「新規マシン追加」やその横の「歯車」ボタンを押しても何も起こらないようです。
![2016-03-01 06 10 18 00001](https://cloud.githubusercontent.com/assets/6257157/13419723/ca1787a2-dfc3-11e5-988a-9b76605d56ae.png)

**Comment by depra95** [comment]
closed https://github.com/eisen-dev/eisen_front/issues/60 .
fixed by https://github.com/eisen-dev/eisen_front/commit/34465c7464edd73bb6c7d294fa2872137a66909f.
