### ISSUE TITLE
Firefox 38.6.1でホストマネージャーの「新規マシン追加」やその横の「歯車」ボタンを押しても何も起こらない

### ISSUE THREAD

**Issue by ytooyama** [eisen-dev/eisen_front#58]
Firefox 38.6.1でホストマネージャーの「add new machine」やその横の「歯車」ボタンを押しても何も起こりません。また、この画面のボタンが「新しいマシンの追加」ではなく、翻訳されていません。

![2016-03-01 06 46 08 00001](https://cloud.githubusercontent.com/assets/6257157/13419897/0452fe14-dfc5-11e5-9855-7b51c9f4b338.png)

**Comment by depra95** [comment]
closed https://github.com/eisen-dev/eisen_front/issues/60 .
fixed by https://github.com/eisen-dev/eisen_front/commit/34465c7464edd73bb6c7d294fa2872137a66909f.
