### ISSUE TITLE
eisen_frontの動作環境と対応ブラウザーを明記する必要がある

### ISSUE THREAD

**Issue by ytooyama** [eisen-dev/eisen_front#62]
eisen Frontがどの環境で動くのか、README.mdに記述しておく必要があると思います。

マルチプラットフォームのブラウザーは大抵同じように動作しますが、
まれにWindows版は動くけどMac版は動かないといったことがあるので注意する必要があると思います。

**Comment by aliceinwire** [comment]
mac化についてpermission以外の問題ありますか。
permissionの問題なら昨日直しました。

**Comment by aliceinwire** [comment]
eisen front と eisen engineは両方vagrantで開発してますので どんなパソコン使っても同じ開発環境になります。
http://raqda.com/vagrant/why-vagrant/index.html

**Comment by ytooyama** [comment]
Firefoxでアクセスしたところ、ボタンなどを押しても何も動かなかったので、このブラウザならどうさしますという情報があるといいなと思い、バグ登録しました

**Comment by aliceinwire** [comment]
問題があったすみませんでした。
バグ登録ありがとうございました。
ボタンのバッグ直していますがmac環境にはあまり関係がないです。

**Comment by aliceinwire** [comment]
これをテストしています。
https://github.com/eisen-dev/eisen_front/issues/60
vagrantにtypescriptからjavascriptをtranspileできます。

**Comment by aliceinwire** [comment]
コミットしました。

**Comment by aliceinwire** [comment]
テストしました。jsファイルができていました。

**Comment by aliceinwire** [comment]
@ytooyama vagrantでjavascriptが作りましたか

**Comment by ytooyama** [comment]
このバグは特定の機能が動かないから立てたバグではありません。
「eisen frontはこのブラウザで動くか確認していますよ」というのを明示してほしかったので立てたバグです。

**Comment by aliceinwire** [comment]
eisen frontはブラウザで動くか確認してもらえます、
ありがとうございます。

**Comment by depra95** [comment]
Eisen Frontendのチェック済みブラウザの明記についての修正https://github.com/eisen-dev/eisen_front/pull/63 をマージしました。
動作OSについては後日検証してからの記載を予定しています。
報告ありがとうございました。
