### ISSUE TITLE
ナビゲーションバーにタイプミスがある

### ISSUE THREAD

**Issue by ytooyama** [eisen-dev/eisen_front#66]
タッゲットホスト→ターゲットホスト

**Comment by ytooyama** [comment]
diff
[diff.txt](https://github.com/eisen-dev/eisen_front/files/155951/diff.txt)
修正したソース
[navigation.php.zip](https://github.com/eisen-dev/eisen_front/files/155954/navigation.php.zip)
※phpファイルをテンンプできないため、zipアーカイブしています。

**Comment by aliceinwire** [comment]
ありがとうございます。

**Comment by aliceinwire** [comment]
@ytooyama アップデートありますか
プルリクエストの作り方は以下：
  1. Fork it   
      ( http://github.com/eisen-dev/eisen_front )  
  2. Create your feature branch (git checkout -b my-new-feature)
  3. Commit your changes (git commit -am 'Add some feature')
  4. Push to the branch (git push origin my-new-feature)
  5. Create new Pull Request

**Comment by aliceinwire** [comment]
Fixed by pull request #79
